server:
  port: 9090

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/commerce/**
          filters:
            - RewritePath=/commerce/(?<segment>.*), /${segment}


      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jjwt:
  secret:
    key: ${JWT_SECRET_KEY}