server:
  port: 9090

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /auth${segment}

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - RewritePath=/products/(?<segment>.*), /commerce${segment}


      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

jjwt:
  secret:
    key: ${JWT_SECRET}