spring.application.name=authentication-service

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/auth-service
spring.datasource.username=postgres
spring.datasource.password=W@ny0
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT
jjwt.secret.key="OTxL!A{jJXz-n4+G$&IOPrb^0mg|8lzhA9HzB5mG<G%"

#SERVER
server.port=8080