#SERVER
server.port=8081

#.env configuration
spring.config.import=optional:file:.env[.properties]

spring.application.name=product-service

#Eureka Client
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#IMAGE SIZE SETTING UPLOAD
#spring.serverlet.multipart.max-file-size=200MB
#spring.serverlet.multipart.max-request-size=200MB