spring.application.name=product-service

#SERVER
server.port=8081

#DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/product-service
spring.datasource.username=postgres
spring.datasource.password=W@ny0
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Eureka Client
eureka.client.service-url.default-zone=http://localhost/8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#IMAGE SIZE SETTING UPLOAD
#spring.serverlet.multipart.max-file-size=200MB
#spring.serverlet.multipart.max-request-size=200MB